export interface StaffMember {
  id: string;
  name: string;
  position: string;
  level: number; // 1=Pimpinan, 2=Wakil/Staff, 3=Guru
  order: number;
  nip?: string | null;
  education?: string | null;
  email?: string | null;
  imageUrl?: string | null;
  active: boolean;
  quote?: string | null;
  subject?: string | null;
  additionalTask?: string | null;
  alumni?: string | null;
}

export const defaultStaffList: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Adang Restuwardani, S.Pd',
    position: 'Kepala Sekolah',
    level: 1,
    order: 1,
    nip: '19680512 199412 1 002',
    education: 'S2 Manajemen Pendidikan',
    imageUrl: '/assets/kepala-sekolah.jpg',
    active: true,
    quote: 'Pendidikan sejati bukan sekadar menorehkan angka, melainkan menyalakan budi pekerti, integritas nurani, dan cinta lingkungan.',
    subject: 'Manajemen Kepemimpinan Satuan Pendidikan',
    additionalTask: 'Penanggung Jawab Utama Mutu Akademik & Karakter Sekolah',
    alumni: 'Universitas Negeri Jakarta (UNJ)',
    email: 'ahmadfauzi@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-2',
    name: 'Hj. Siti Rahayu, S.Pd.',
    position: 'Wakil Kepala Sekolah Bidang Kurikulum',
    level: 2,
    order: 2,
    nip: '19700215 199512 2 001',
    education: 'S1 Pendidikan Bahasa Indonesia',
    active: true,
    quote: 'Kurikulum yang bermakna memerdekakan siswa untuk berpikir kritis, berani berkarya, dan tumbuh sesuai kodrat zamannya.',
    subject: 'Bahasa Indonesia & Kurikulum Merdeka',
    additionalTask: 'Koordinator Tim Pengembang Kurikulum Operasional Satuan Pendidikan (KOSP)',
    alumni: 'Universitas Sultan Ageng Tirtayasa (Untirta)',
    email: 'sitirahayu@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-3',
    name: 'Drs. Bambang Susilo',
    position: 'Wakil Kepala Sekolah Bidang Kesiswaan',
    level: 2,
    order: 3,
    nip: '19690520 199403 1 002',
    education: 'S1 Pendidikan Jasmani, Kesehatan & Rekreasi',
    active: true,
    quote: 'Kebugaran fisik dan sportivitas adalah bekal utama pembentukan mental pejuang yang berintegritas tinggi.',
    subject: 'Pendidikan Jasmani, Olahraga, & Kesehatan (PJOK)',
    additionalTask: 'Pembina Kedisiplinan Siswa & Koordinator Kontingen Olahraga',
    alumni: 'Universitas Pendidikan Indonesia (UPI Bandung)',
    email: 'bambangsusilo@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-4',
    name: 'Endang Supriatna, S.Pd.',
    position: 'Wakil Kepala Sekolah Bidang Sarana & Prasarana',
    level: 2,
    order: 4,
    nip: '19710310 199503 1 001',
    education: 'S1 Pendidikan Matematika',
    active: true,
    quote: 'Lingkungan belajar yang asri, nyaman, dan ramah anak menjadi ruang tumbuh terbaik bagi generasi pembaharu.',
    subject: 'Matematika & Geometri Terapan',
    additionalTask: 'Koordinator Penataan Fasilitas Sekolah & Sarpras Ramah Lingkungan',
    alumni: 'Universitas Pakuan Bogor',
    email: 'endangsupriatna@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-5',
    name: 'Yayah Nurhayati, S.Pd.',
    position: 'Wakil Kepala Sekolah Bidang Humas',
    level: 2,
    order: 5,
    nip: '19720425 199602 2 001',
    education: 'S1 Pendidikan Ilmu Pengetahuan Sosial',
    active: true,
    quote: 'Sinergi hangat antara sekolah, keluarga, dan masyarakat adalah kunci kebahagiaan belajar anak-anak kita.',
    subject: 'Ilmu Pengetahuan Sosial (IPS)',
    additionalTask: 'Penghubung Kemitraan Komite Sekolah, Orang Tua, & Humas Kedinasan',
    alumni: 'Universitas Negeri Semarang (UNNES)',
    email: 'yayahnurhayati@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-6',
    name: 'Asep Kurniawan, S.Pd.',
    position: 'Guru Matematika & Pembina OSIS',
    level: 3,
    order: 6,
    nip: '19780102 200301 1 001',
    education: 'S1 Pendidikan Matematika',
    active: true,
    quote: 'Setiap soal memiliki jalan keluar. Belajar matematika adalah seni melatih kesabaran dan ketajaman logika.',
    subject: 'Matematika Aljabar & Statistika Dasar',
    additionalTask: 'Pembina Organisasi Siswa Intra Sekolah (OSIS) & Pramuka Penggalang',
    alumni: 'Universitas Sultan Ageng Tirtayasa (Untirta)',
    email: 'asepkurniawan@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-7',
    name: 'Dewi Lestari, S.Pd.',
    position: 'Guru Bahasa Indonesia & Literasi',
    level: 3,
    order: 7,
    nip: '19790214 200401 2 001',
    education: 'S1 Pendidikan Bahasa & Sastra Indonesia',
    active: true,
    quote: 'Membaca memperluas cakrawala, menulis mengikat ilmu dan menyuarakan gagasan luhur generasi muda.',
    subject: 'Bahasa Indonesia & Apresiasi Sastra',
    additionalTask: 'Koordinator Gerakan Literasi Sekolah (GLS) & Majalah Dinding Digital',
    alumni: 'Universitas Siliwangi (UNSIL)',
    email: 'dewilestari@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-8',
    name: 'Rudi Hermawan, S.Pd.',
    position: 'Guru IPA & Kepala Lab IPA',
    level: 3,
    order: 8,
    nip: '19800320 200401 1 001',
    education: 'S1 Pendidikan Fisika & Sains Terapan',
    active: true,
    quote: 'Eksperimen sains membuktikan bahwa rasa ingin tahu yang terarah melahirkan penemuan-penemuan besar.',
    subject: 'Ilmu Pengetahuan Alam (Fisika & Kimia Dasar)',
    additionalTask: 'Kepala Laboratorium Sains Terpadu & Pembina Olimpiade Sains (OSN IPA)',
    alumni: 'Universitas Pendidikan Indonesia (UPI Bandung)',
    email: 'rudihermawan@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-9',
    name: 'Nia Sari, S.Pd.',
    position: 'Guru IPS & Koordinator Adiwiyata',
    level: 3,
    order: 9,
    nip: '19810505 200501 2 001',
    education: 'S1 Pendidikan Geografi & IPS Terpadu',
    active: true,
    quote: 'Menyayangi alam bukan pilihan, melainkan kewajiban moral setiap insan yang beradab dan beriman.',
    subject: 'Ilmu Pengetahuan Sosial & Mitigasi Kebencanaan',
    additionalTask: 'Koordinator Pokja Sekolah Peduli & Berbudaya Lingkungan Hidup (Adiwiyata)',
    alumni: 'Universitas Indraprasta PGRI (UNINDRA)',
    email: 'niasari@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-10',
    name: 'Agus Pratama, S.Pd.',
    position: 'Guru Bahasa Inggris',
    level: 3,
    order: 10,
    nip: '19790615 200301 1 002',
    education: 'S1 Pendidikan Bahasa Inggris',
    active: true,
    quote: 'Language connects worlds. Speak with confidence and let your voice inspire the global community.',
    subject: 'Bahasa Inggris Komunikatif (English Conversation & Literacy)',
    additionalTask: 'Pembina English Club & Koordinator Pertukaran Pembelajaran Budaya',
    alumni: 'Universitas Islam Negeri (UIN) Syarif Hidayatullah Jakarta',
    email: 'aguspratama@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-11',
    name: 'Leni Marlina, S.Pd.',
    position: 'Guru Seni Budaya & Pembina Karawitan',
    level: 3,
    order: 11,
    nip: '19820730 200601 2 001',
    education: 'S1 Pendidikan Seni Tari & Budaya Tradisional',
    active: true,
    quote: 'Kesenian adalah cermin kelembutan budi, melestarikan tradisi luhur tanah Lebak di tengah arus modernisasi.',
    subject: 'Seni Budaya, Musik Tradisional & Kriya Daerah',
    additionalTask: 'Pembina Sanggar Seni Siswa & Pelatih Tari Rampak Kendang',
    alumni: 'Institut Seni Budaya Indonesia (ISBI Bandung)',
    email: 'lenimarlina@smpn5cibeber.sch.id',
  },
  {
    id: 'staff-12',
    name: 'Hendra Gunawan, S.Kom.',
    position: 'Guru Informatika & Teknisi Lab Komputer',
    level: 3,
    order: 12,
    nip: '19840915 200701 1 001',
    education: 'S1 Teknik Informatika & Rekayasa Perangkat Lunak',
    active: true,
    quote: 'Kuasai teknologi untuk menciptakan solusi nyata, bukan sekadar menjadi konsumen di era serba digital.',
    subject: 'Informatika, Pemrograman Dasar & Literasi Digital',
    additionalTask: 'Kepala Lab Komputer & Penanggung Jawab Teknis Asesmen Nasional (ANBK)',
    alumni: 'Universitas Bina Nusantara (Binus University)',
    email: 'hendragunawan@smpn5cibeber.sch.id',
  },
];

